import {
	authorize,
	checkUserLoginExists,
	logout,
	register,
	updateUser,
	getAccounts,
	getCategories,
	getAccountIcons,
	updateAccount,
	deleteAccount,
	createAccount,
	updateCategory,
	deleteCategory,
	createCategory,
	getIcons,
	getIncomeOperation,
} from './operations'

export const server = {
	authorize,
	checkUserLoginExists,
	logout,
	register,
	updateUser,
	getAccounts,
	getCategories,
	getAccountIcons,
	updateAccount,
	deleteAccount,
	createAccount,
	updateCategory,
	deleteCategory,
	createCategory,
	getIcons,
	getIncomeOperation,
}
