import {
	authorize,
	checkUserLoginExists,
	logout,
	register,
	updateUser,
	getAccounts,
	getCategories,
	getAccountIcons,
	updateAccount,
	deleteAccountData,
	createAccount,
	updateCategory,
	deleteCategoryData,
	createCategory,
} from './operations'

export const server = {
	authorize,
	checkUserLoginExists,
	logout,
	register,
	updateUser,
	getAccounts,
	getCategories,
	getAccountIcons,
	updateAccount,
	deleteAccountData,
	createAccount,
	updateCategory,
	deleteCategoryData,
	createCategory,
}
