export const DEFAULT_CATEGORIES = [
	{
		id: 'd001',
		type: 'income',
		name: 'Зарплата',
		icon: 'cc-mastercard',
		color: 'c7c9c10',
	},
	{
		id: 'd002',
		type: 'income',
		name: 'Банк',
		icon: 'university',
		color: 'c7c9c10',
	},
	{
		id: 'd003',
		type: 'income',
		name: 'Другое',
		icon: 'question-circle',
		color: 'c7c9c10',
	},
	{
		id: 'd004',
		type: 'expense',
		name: 'Дом',
		icon: 'home',
		color: 'c7c9c10',
	},
	{
		id: 'd005',
		type: 'expense',
		name: 'Питомец',
		icon: 'paw',
		color: 'c7c9c10',
	},
	{
		id: 'd006',
		type: 'expense',
		name: 'Транспорт',
		icon: 'bus',
		color: 'c7c9c10',
	},
	{
		id: 'd007',
		type: 'expense',
		name: 'Здоровье',
		icon: 'heartbeat',
		color: 'c7c9c10',
	},
	{
		id: 'd008',
		type: 'expense',
		name: 'Развлечения',
		icon: 'glass',
		color: 'c7c9c10',
	},
	{
		id: 'd009',
		type: 'expense',
		name: 'Другое',
		icon: 'question-circle',
		color: 'c7c9c10',
	},
]
