export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	UPDATE_USER: 'UPDATE_USER',

	SET_ACCOUNTS: 'SET_ACCOUNTS',
	RESET_ACCOUNTS: 'RESET_ACCOUNTS',
	SET_ACCOUNT: 'SET_ACCOUNT',
	UPDATE_ACCOUNT: 'UPDATE_ACCOUNT',
	DELETE_ACCOUNT: 'DELETE_ACCOUNT',

	SET_CATEGORIES: 'SET_CATEGORIES',
	RESET_CATEGORIES: 'RESET_CATEGORIES',
	SET_CATEGORY: 'SET_CATEGORY',
	UPDATE_CATEGORY: 'UPDATE_CATEGORY',
	DELETE_CATEGORY: 'DELETE_CATEGORY',
}
